spring:
  application:
    name: coldchainos
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5438/coldchainos_db
    username: coldchain_admin
    password: coldchain_secret_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      pool-name: ColdChainHikariPool

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

coldchainos:
  outbox:
    relay-interval-ms: 2000

server:
  port: 8080
