apiVersion: v1
kind: ConfigMap
metadata:
  name: coldchainos-config
  namespace: coldchainos
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-cluster.database.svc.cluster.local:5432/coldchainos_db?prepareThreshold=5&reWriteBatchedInserts=true"
  REDIS_HOST: "redis-cluster.cache.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  DB_POOL_MAX: "50"
  DB_POOL_MIN_IDLE: "10"
  TRACING_PROBABILITY: "0.1"
