apiVersion: v1
kind: Secret
metadata:
  name: coldchainos-secrets
  namespace: coldchainos
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "coldchain_admin"
  SPRING_DATASOURCE_PASSWORD: "change_me_in_production_vault"
  REDIS_PASSWORD: "change_me_in_production_vault"
  COLDCHAIN_SECURITY_JWT_SECRET: "c2VjdXJlX3Byb2R1Y3Rpb25faG1hY19zaGEyNTZfc2VjcmV0X2tleV9leHRyZW1lbHlfbG9uZ19zdHJpbmc="
